### ISSUE TITLE
Observation: cannot redefine the "medicationXChanged" extensions

### ISSUE THREAD

**Issue by qligier** [CARA-ch/ch-emed-epr#1]
The medicationStatementChanged and medicationRequestChanged extensions are references to CHEMEDMedicationStatement and CHEMEDMedicationRequest.

We need to change them to references to CHEMEDEPRMedicationStatement and CHEMEDEPRMedicationRequest here. How can it be done?
We can't update the extension directly. If we extend the extensions, we have to remove the old ones from the Observation and add the new ones. The issue with that is the constraint that specifically checks for the extension URL. Also, it would not be compatible with CH-EMED.

@ziegm Any idea on how to do it?

**Comment by ziegm** [comment]
Oh, that's a good hint. I'll have to change the constraint so that it doesn't check the URL, but whether an entry is present and 'conformsTo' the profiles of the extension.

**Comment by ziegm** [comment]
@qligier 
could you please check, if it works for you with the updated constraint:
http://build.fhir.org/ig/hl7ch/ch-emed/branches/204_obs-constraint/StructureDefinition-ch-emed-observation.html#constraints

**Comment by qligier** [comment]
Thank you!
Now I can override the extensions, but would we be still compatible? Having different extension URLs means more work for implementers, who will have to check for the resources instead of the URL.

Another way to solve this issue could be:

1. I keep the CH-EMED extensions. In the column Type, the CH-EMED types are shown, I update the short to specifically say that the CH-EMED-EPR resources are expected.
2. I add another constraint (or two), checking that the extensions refer to the CH-EMED-EPR resources.

What do you think?

**Comment by ziegm** [comment]
You are right with the compatibility... 
In that case, do you agree with no changes in CH EMED and updates on your side?

**Comment by qligier** [comment]
It seems to be the best solution to ensure compatibility (as far as I know), so yes, I'll update the resources here.

**Comment by qligier** [comment]
Already solved with two additional constraints.
