### ISSUE TITLE
Address EPRTime extension usage

### ISSUE THREAD

**Issue by dvribeira** [CARA-ch/ch-emed-epr#25]
The following changes would align the specs with the code regarding authorship timestamps:

- Add `EPRTime` extension with cardinality `1..1` to:
    - `CHEMEDEPRMedicationStatementCard.informationSource`
    - `CHEMEDEPRMedicationStatementList.informationSource`
    - `CHEMEDEPRMedicationRequestList.requester`
    - `CHEMEDEPRMedicationDispenseList.performer.actor`
    - `CHEMEDEPRObservationList.performer`
- Add `EPRTime` extension with cardinality `0..1` to:
    - `CHEMEDEPRCompositionMedicationTreatmentPlan.section[treatmentPlan].author`
    - `CHEMEDEPRCompositionMedicationPrescription.section[prescription].author`
    - `CHEMEDEPRCompositionMedicationDispense.section[dispense].author`
    - `CHEMEDEPRCompositionPharmaceuticalAdvice.section[pharmaceuticalAdvice].author`

**Comment by dvribeira** [comment]
I will propose the same changes to CH-EMED and depending on the feedback we might just wait for the changes to be done upstream. Otherwise and again depending on the feedback, we might just implement these in CH-EMED-EPR or change to align to any other proposed solution by CH-EMED.

**Comment by qligier** [comment]
We have removed the ch-ext-epr-time in https://github.com/hl7ch/ch-emed/pull/165 because it seemed of limited usefulness at the time.
What is the use case for the authorship timestamp? What is the difference with the document creation time?

**Comment by dvribeira** [comment]
For PML and PMLC, we are not providing the documents or compositions themselves, so it is a way of specifying the time of authorship, otherwise not present anywhere. This is needed for PDF generation and I guess useful information to have in PML documents as well.

For the provided documents, its usefulness is indeed arguable, but the extension is already there (0..1) for the composition.author so I thought it would be coherent to have it, also optional, on the section author, in case a different timestamp can be specified for the medical authorship. The PMP code will treat these optional timestamps as follows:

- the entry's document authorship will be the composition.author.time if specified, otherwise the document's timestamp.
- the entry's medical authorship will be the composition.section.author.time if specified, otherwise the document authorship's timestamp as resolved above.

**Comment by qligier** [comment]
For the provided documents: the `Composition.date` [is described as](https://www.hl7.org/fhir/documents.html) _when the author wrote the document logically_. Is it really different from the time of authorship?


For the PML/PMLC documents: the items have datetime fields that could cover that use case too, e.g. `MedicationStatement.dateAsserted` or `MedicationRequest.authoredOn`. Could that be enough?

**Comment by dvribeira** [comment]
For the generated documents, yes I also thought about the possibility of using those fields but after discussing it with Stéphane, but:

- Those elements are already supported in the provided documents, with the exception of the MedicationStatement.dateAsserted, if we are going to use these fields in the generated documents, then we need to either also specify that is one is not supported for the MTP doc or we add rules to ensure they match the document timestamp if we go for "there is only one authorship timestamp" per bundle. This is not a big issue, it could be done.
- At the moment, things have been done so that we use authorship information from the composition only, hence the removal of support for the author fields in the entries and the use of composition.author and composition.section.author as specified in the ch-emed guidelines. We thought it was coherent to keep this the same. Since composition.author and documentAuthor have explicitly the time extension in the ch-emed specs we thought it was natural to do the same with the medical author fields.
- We do not know if any of the other fields might have a meaning not necessarily tied to authorship, i.e. "whenHandedOver". Although we could assume they can be used for authorship timestamp.
- Regarding if we should make a difference between document authorship timestamp and medical authorship timestamp, it seems that since the moment you might have both, their timestamps might be different and hence should be recorded (if different), otherwise why have a time extension in composition.author and documentAuthor at all? Furthermore, our understanding of the profiles, e.g. https://www.ihe.net/uploadedFiles/Documents/Pharmacy/IHE_Pharmacy_Suppl_MTP.pdf is that even if the author itself is the same, differences in timestamp between the document authorship and the medical authorship could exist and should be supported.
![image](https://github.com/CARA-ch/ch-emed-epr/assets/133101442/8b814c68-28a5-41dc-94d9-0670b7ea1f1a)

Please let me know if you think I am forgetting or missing the point over something.

**Comment by dvribeira** [comment]
Feedback from professionals on whether the timestamp of the medical authorship is relevant or not is needed.

**Comment by ziegm** [comment]
@dvribeira where did you find the still used extension in ch emed?

**Comment by dvribeira** [comment]
In the author slices of all the stable document compositions:
![image](https://github.com/CARA-ch/ch-emed-epr/assets/133101442/5c91d2c7-b898-4523-bfc0-7d4baf86ac02)

For PML composition:
- in `dataEnterer`:
![image](https://github.com/CARA-ch/ch-emed-epr/assets/133101442/39626e2e-4b37-4df0-a928-c6d26d78d5cd)
![image](https://github.com/CARA-ch/ch-emed-epr/assets/133101442/4a06b872-2fb4-4b3f-98a7-544f1656841c)
- in `author`:
![image](https://github.com/CARA-ch/ch-emed-epr/assets/133101442/e30d6f6d-fb7e-4d3c-b955-3f2acbf90bce)

For PMLC composition:
- as for PML composition, in `dataEnterer`
- as for PML composition in `author`

For PMLC CHEMEDMedicationStatementCard:
- in `authorDocument`:
![image](https://github.com/CARA-ch/ch-emed-epr/assets/133101442/0d5f8122-76df-4894-90b9-5fac01c033c9)
![image](https://github.com/CARA-ch/ch-emed-epr/assets/133101442/8fb3e9a4-7bfd-4e2c-9249-9208795552aa)

**Comment by ziegm** [comment]
OK, thanks! But that is inherited from CH Core, and therefore shown in the Snapshot Table. We can't change anything in the CH EMED IG. If we do not have the Extensions somewhere described or used in the examples, I would suggest to leave it as it is, because that's the way IG dependencies work.

**Comment by dvribeira** [comment]
Understood.

In the meantime, the [meager] professional feedback we have had so far is that the two timestamps (document authorship and medical authorship) should be kept. If the policy is to avoid using the time extension, then the only choice without further altering the IG structure is to use the following fields:
- MTP: 
  - document: `CHEMEDEPRCompositionMedicationTreatmentPlan.date`
  - medical (if present): `CHEMEDEPRMedicationStatement.dateAsserted` (currently flagged as not supported, flag should be removed)
- PRE: 
  - document: `CHEMEDEPRCompositionMedicationPrescription.date`
  - medical (if present): `CHEMEDEPRMedicationRequest.authoredOn`
- DIS: 
  - document: `CHEMEDEPRCompositionMedicationDispense.date`
  - medical (if present): `CHEMEDEPRMedicationDispense.whenHandedOver`
- PADV: 
  - document: `CHEMEDEPRCompositionPharmaceuticalAdvice.date`
  - medical (if present): `CHEMEDEPRObservation.issued`
  - `CHEMEDMedicationStatementChanged`:
    - document: `CHEMEDEPRCompositionPharmaceuticalAdvice.date`
    - medical (if present): `CHEMEDMedicationStatementChanged.dateAsserted`
  - `CHEMEDMedicationRequestChanged`:
    - document: `CHEMEDEPRCompositionPharmaceuticalAdvice.date`
    - medical (if present): `CHEMEDMedicationRequestChanged.authoredOn`
- PML:
  - `CHEMEDEPRMedicationStatementList`:
    - document (if different from medical): ? should we use the time extension on documentAuthor?
    - medical: `.dateAsserted` (currently flagged as not supported) (cardinality should be changed to 1..1)
  - `CHEMEDEPRMedicationRequestList`:
    - document (if present): ? should we use the time extension on documentAuthor?
    - medical: `.authoredOn` (cardinality should be changed to 1..1)
  - `CHEMEDEPRMedicationDispenseList`:
    - document (if present): ? should we use the time extension on documentAuthor?
    - medical: `.whenHandedOver` (cardinality should be changed to 1..1)
  - `CHEMEDEPRObservationList`:
    - document (if present): ? should we use the time extension on documentAuthor? otherwise no field available
    - medical: `.issued` (cardinality should be changed to 1..1)
    - `CHEMEDMedicationStatementChanged`:
      - document: not provided, use `CHEMEDEPRObservationList`'s if provided.
      - medical: `.dateAsserted` (we use the same profile as for provided PADV entries, is it worth just to specify 1..1 cardinality?)
    - `CHEMEDMedicationStatementChanged`:
      - document: not provided, use `CHEMEDEPRObservationList`'s if provided.
      - medical: `.authoredOn` (we use the same profile as for provided PADV entries, is it worth just to specify 1..1 cardinality?)
- PMLC:
  - `CHEMEDEPRMedicationStatementCard`:
    - document (if different from medical): ? should we use the time extension on documentAuthor? otherwise no field available
    - medical: `.dateAsserted` (currently flagged as not supported) (cardinality should be changed to 1..1)
Consequences:
- Authorship information is now split between composition and entry.
- PML and PMLC entries lack a document authorship timestamp field unless using the time extension on documentAuthor, but is the document authorship timestamp relevant here? It is stored with the documents and available upon request, would this suffice?

**Comment by dvribeira** [comment]
This is now somehow related to this open issue on CH-EMED: https://github.com/hl7ch/ch-emed/issues/241

**Comment by dvribeira** [comment]
Dealt with by changes to authorship to CH EMED and integrated with #39
