### ISSUE TITLE
Removal of CH EMED profiles to CH Core

### ISSUE THREAD

**Issue by dvribeira** [CARA-ch/ch-emed-epr#56]
Certain profiles from CH EMED will be moved to CH Core:
https://github.com/hl7ch/ch-emed/issues/258
https://github.com/hl7ch/ch-core/issues/119

Verify impact and address any issues.

**Comment by ziegm** [comment]
@dvribeira probably no impact, because the CH EMED profiles will stay (just derived afterward from a CH Core base profile)

**Comment by dvribeira** [comment]
@ziegm yes I thought so, thanks!
