### ISSUE TITLE
HL7 International announcement: Previous Version Comparison & mandatory OIDs for CodeSystems and ValueSets

### ISSUE THREAD

**Issue by dvribeira** [CARA-ch/ch-emed-epr#63]
Are we affected by this announcement? https://chat.fhir.org/#narrow/stream/179294-committers.2Fannounce/topic/FMG.20Policy.20Announcements

> Grahame Grieve: FMG made two decisions of relevance to IG Authors today.
> 
>     Policy around adding Previous Version Comparison
>     Need to assign OIDs to CodeSystems and ValueSets

This will be enforced on all HL7 International publications.

**Comment by oliveregger** [comment]
no i don't think so, we do not go throught the international ballot process with our ig's
