### ISSUE TITLE
Forbid mixing units in statement/request dosage

### ISSUE THREAD

**Issue by dvribeira** [CARA-ch/ch-emed-epr#75]
See https://github.com/CARA-ch/pmp-issues/issues/39

**Comment by dvribeira** [comment]
It should be decided whether it is better to just forbid the unit field for split dosage elements or to enforce that it is the same as the one in the base dosage (including absent if absent and present if present).

More inclined towards the second choice, even if it adds a bit of complexity with the invariant.

**Comment by qligier** [comment]
I agree with the second choice; the first one is not really FHIR-compatible
